# Generated by Django 5.2.6 on 2025-09-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin Added'), ('dataset', 'Dataset Imported')], default='dataset', max_length=10),
        ),
    ]
