# Generated by Django 5.2.3 on 2025-07-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_bookrating_cartitem_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
