# Generated by Django 5.2.4 on 2025-07-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_image'),
        ('books', '0004_book_quantity'),
    ]

    operations = [
    ]
