# Generated by Django 5.2.3 on 2025-08-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_genre_book_genres"),
        ("books", "0005_merge_0002_alter_book_cover_image_0004_book_quantity"),
    ]

    operations = []
