# Generated by Django 5.2.3 on 2025-08-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_merge_20250807_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
    ]
