# Generated by Django 5.2.4 on 2025-08-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_book_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="books.book",
                    ),
                ),
                (
                    "recommended_books",
                    models.ManyToManyField(
                        related_name="recommended_for", to="books.book"
                    ),
                ),
            ],
        ),
    ]
