# Generated by Django 5.2.6 on 2025-09-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_bookrecommendation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="book",
            name="description",
        ),
        migrations.DeleteModel(
            name="BookRecommendation",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
