# Generated by Django 5.2.6 on 2025-09-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_remove_book_genres_remove_book_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="year_of_publication",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
