# Generated by Django 5.2.6 on 2025-09-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_book_year_of_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookrating",
            name="book",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="books.book"
            ),
        ),
    ]
