# Generated by Django 5.2.3 on 2025-08-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0002_order_email_order_payment_method_order_shipping_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.CharField(
                blank=True, editable=False, max_length=24, null=True, unique=True
            ),
        ),
    ]
