# Generated by Django 5.2.6 on 2025-09-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_intent_id',
        ),
    ]
