# Generated by Django 5.2.4 on 2025-08-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("esewa", "E-Sewa"),
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("stripe", "Stripe"),
                ],
                default="cash_on_delivery",
                max_length=20,
            ),
        ),
    ]
